---
platform: linux

image_resource:
  type: mock
  source: {mirror_self: true}

run:
  path: sh
  args:
  - -c
  - |
    until test -f /tmp/stop-waiting; do
      echo 'waiting for /tmp/stop-waiting to exist'
      sleep 1
    done

    echo done
